
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rohit
 */
public class FirstScreen extends javax.swing.JFrame {
    public boolean optionsChecked = false;
    public int noOfPlayers = 0;
    public int level = 0;
    public int theme = 0;
    public int maxPoints = 5;


    /**
     * Creates new form FirstScreen
     */
    public FirstScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1240, 677));
        setMinimumSize(new java.awt.Dimension(1240, 677));
        setPreferredSize(new java.awt.Dimension(1240, 677));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(48, 206, 255));
        jPanel1.setLayout(null);

        jButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton4.setFont(new java.awt.Font("Rosewood Std", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(2, 29, 36));
        jButton4.setText("Single Player");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(540, 360, 167, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/Rohit/Desktop/pong.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 120, 505, 168);

        jButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton7.setFont(new java.awt.Font("Rosewood Std", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(2, 29, 36));
        jButton7.setText("Multi Player");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(540, 410, 167, 40);

        jButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton8.setFont(new java.awt.Font("Rosewood Std", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(2, 29, 36));
        jButton8.setText("Options");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(540, 460, 167, 40);

        jButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton9.setFont(new java.awt.Font("Rosewood Std", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(2, 29, 36));
        jButton9.setText("Quit");
        jPanel1.add(jButton9);
        jButton9.setBounds(540, 510, 167, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/Rohit/Downloads/background.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -70, 1240, 750);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
       
        if(optionsChecked == false){
            optionsChecked = true;
            this.getContentPane().remove(jPanel1);
          OptionsPanel options = new OptionsPanel();
          this.getContentPane().add(options, "card3");
          this.pack();
        }
        // TODO add your handling code here:
//        System.out.println("Mouse Clicked");
//        this.getContentPane().remove(jPanel1);
//        OptionsPanel options = new OptionsPanel();
//        this.getContentPane().add(options, "card3");
//        this.pack();

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:    FOR MULTI PLAYER
        noOfPlayers = 2;
        System.out.println(noOfPlayers +" " + level +" "+ theme+ " " + maxPoints);
        FirstScreen.fScreen.setVisible(false);
        Game game = new Game(noOfPlayers,level,theme,maxPoints);
//        fScreen.getContentPane().removeAll();
//        fScreen.add(game1);
        pack();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:    FOR SINGLE PLAYER
        noOfPlayers = 1;
        System.out.println(noOfPlayers +" " + level +" "+ theme+ " " + maxPoints);
        FirstScreen.fScreen.setVisible(false);
        Game game = new Game(noOfPlayers,level,theme,maxPoints);
        //fScreen.getContentPane().removeAll();
        //fScreen.add(game1);
        pack();
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fScreen = new FirstScreen();
                fScreen.setVisible(true);
            }
        });
    }

    public static FirstScreen fScreen;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


//    optionsChecked = false;
//        fScreen.getContentPane().removeAll();
//        fScreen.initComponents();
    
  public class OptionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton1.setText("Hard");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(650, 100, 180, 50);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LEVEL");
        add(jLabel2);
        jLabel2.setBounds(500, 40, 120, 40);

        jButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton4.setText("Easy");
        jButton4.setActionCommand("Easy");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyClicked(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(290, 100, 180, 50);

        jButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton5.setText("Medium");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumClicked(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(470, 100, 180, 50);

        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton2.setText("Water");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waterClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(650, 260, 180, 50);

        jButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton6.setText("Fire");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireClicked(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(290, 260, 180, 50);

        jButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton7.setText("Classic");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classicClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(470, 260, 180, 50);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("THEME");
        add(jLabel4);
        jLabel4.setBounds(500, 210, 130, 40);

        jButton3.setFont(new java.awt.Font("Rosewood Std", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("/Users/Rohit/Downloads/backicon.png")); // NOI18N
        jButton3.setText("Back");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backClicked(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(500, 480, 120, 50);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MAX POINTS ");
        add(jLabel5);
        jLabel5.setBounds(450, 360, 246, 43);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(level + "");
        add(jLabel1);
        jLabel1.setBounds(550, 420, 24, 30);

        jButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uparrow.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(610, 410, 40, 40);

        jButton10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/downarrow.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10);
        jButton10.setBounds(470, 410, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optionsbackground.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1120, 630);
        
        if(level == 0){
         jButton4.setBackground(new Color(48,206,255));            
        }else if(level == 1){
         jButton5.setBackground(new Color(48,206,255));           
        }else if(level == 2){
         jButton1.setBackground(new Color(48,206,255));           
        }
        
        if(theme == 0){
         jButton7.setBackground(new Color(48,206,255));            
        }else if(theme == 1){
         jButton6.setBackground(new Color(48,206,255));           
        }else if(theme == 2){
         jButton2.setBackground(new Color(48,206,255));           
        }
        
        jLabel1.setText(maxPoints + "");           
       
    }// </editor-fold>                                

    
    private void easyClicked(java.awt.event.MouseEvent evt) {                             
        // TODO add your handling code here:
        level = 0;
        
        jButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton4.setBackground(new Color(48,206,255)); 
    }                            

    private void mediumClicked(java.awt.event.MouseEvent evt) {                               
        // TODO add your handling code here:
        level = 1;
        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton5.setBackground(new Color(48,206,255));
       
    }                              

    private void hardClicked(java.awt.event.MouseEvent evt) {                             
        // TODO add your handling code here:
        level = 2;
        jButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton1.setBackground(new Color(48,206,255));
       
    }                            

    private void fireClicked(java.awt.event.MouseEvent evt) {                             
        // TODO add your handling code here:
        theme = 1;
        jButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton6.setBackground(new Color(48,206,255));
      
    }                            

    private void classicClicked(java.awt.event.MouseEvent evt) {                                
        // TODO add your handling code here:
        theme = 0;
        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton7.setBackground(new Color(48,206,255));
      
    }                               

    private void waterClicked(java.awt.event.MouseEvent evt) {                              
        // TODO add your handling code here:
        theme = 2;
        jButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        jButton2.setBackground(new Color(48,206,255));
      
    }                             

    private void backClicked(java.awt.event.MouseEvent evt) {                             
        // TODO add your handling code here:
        optionsChecked = false;
        fScreen.getContentPane().removeAll();
        fScreen.initComponents();
    }                            

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }     
    
      private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        if(maxPoints > 0 ){
            maxPoints--;
        }
         jLabel1.setText(maxPoints + "");

    }                                      

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
         maxPoints++;
         jLabel1.setText(maxPoints + "");           
    }                                     



    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration                   
}

}
